#!/usr/bin/env python3
"""Create a deterministic Markdown snapshot from an Engram graph artifact."""

from __future__ import annotations

import argparse
import json
import logging
from collections import Counter
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any


LOGGER = logging.getLogger(__name__)
GRAPH_TYPES = ("Concept", "Method", "Technology", "Domain")


def normalized_node(node: Mapping[str, Any]) -> dict[str, Any]:
    """Flatten Graphology-style node attributes while preserving ordinary nodes."""
    attributes = node.get("attributes")
    flattened = dict(attributes) if isinstance(attributes, Mapping) else {}
    flattened.update({key: value for key, value in node.items() if key != "attributes"})
    if "id" not in flattened and isinstance(flattened.get("key"), str):
        flattened["id"] = flattened["key"]
    return flattened


def graph_nodes(graph: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Return nodes from standard or Graphology-style serialized graphs."""
    raw_nodes = graph.get("nodes", [])
    if isinstance(raw_nodes, Mapping):
        raw_nodes = [
            {"key": key, "attributes": value} if isinstance(value, Mapping) else {"key": key}
            for key, value in raw_nodes.items()
        ]
    if not isinstance(raw_nodes, list):
        return []
    return [normalized_node(node) for node in raw_nodes if isinstance(node, Mapping)]


def node_type(node: Mapping[str, Any]) -> str:
    """Return an ontology type across Engram's supported serializations."""
    for field in ("node_type", "type", "kind", "category"):
        value = node.get(field)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def node_label(node: Mapping[str, Any]) -> str:
    """Return a stable display label for a node."""
    for field in ("label", "title", "name", "id", "key"):
        value = node.get(field)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return "Untitled node"


def edge_endpoints(edge: Mapping[str, Any]) -> tuple[str, str] | None:
    """Extract endpoint IDs from regular or Graphology-style serialized edges."""
    source = edge.get("source")
    target = edge.get("target")
    if isinstance(source, str) and isinstance(target, str):
        return source, target
    attributes = edge.get("attributes")
    if isinstance(attributes, Mapping):
        source = attributes.get("source")
        target = attributes.get("target")
        if isinstance(source, str) and isinstance(target, str):
            return source, target
    return None


def connection_counts(graph: Mapping[str, Any]) -> Counter[str]:
    """Count each node's incident edges without assuming a graph direction."""
    counts: Counter[str] = Counter()
    raw_edges = graph.get("edges", [])
    if isinstance(raw_edges, Mapping):
        raw_edges = raw_edges.values()
    if not isinstance(raw_edges, Iterable):
        return counts
    for edge in raw_edges:
        if not isinstance(edge, Mapping):
            continue
        endpoints = edge_endpoints(edge)
        if endpoints is None:
            continue
        counts.update(endpoints)
    return counts


def markdown_link(label: str, url: object) -> str:
    """Render a safe Markdown link when a paper has an http(s) URL."""
    escaped_label = label.replace("[", "\\[").replace("]", "\\]")
    if isinstance(url, str) and url.startswith(("https://", "http://")):
        return f"[{escaped_label}]({url})"
    return f"[{escaped_label}](#)"


def date_value(node: Mapping[str, Any]) -> str:
    """Choose a sortable displayed date from optional source fields."""
    for field in ("date_added", "date", "year"):
        value = node.get(field)
        if isinstance(value, (int, float)):
            return str(int(value))
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def typed_nodes(nodes: Iterable[Mapping[str, Any]], expected_type: str) -> list[Mapping[str, Any]]:
    """Select nodes by type, case-insensitively."""
    return [node for node in nodes if node_type(node).casefold() == expected_type.casefold()]


def build_summary(graph: Mapping[str, Any], limit: int = 5) -> str:
    """Build a deterministic Markdown fragment suitable for inclusion in Quarto."""
    nodes = graph_nodes(graph)
    counts = connection_counts(graph)
    lines = [
        "<!-- Generated by scripts/generate_research_summary.py. Do not edit by hand. -->",
        "## Research graph snapshot",
    ]

    if not nodes:
        lines.extend(["", "No typed nodes are available yet."])
        return "\n".join(lines) + "\n"

    for expected_type in GRAPH_TYPES:
        entries = typed_nodes(nodes, expected_type)
        if not entries:
            continue
        ranked = sorted(
            entries,
            key=lambda node: (
                -counts[
                    node_label(node)
                    if not isinstance(node.get("id"), str)
                    else node["id"]
                ],
                node_label(node).casefold(),
            ),
        )[:limit]
        lines.extend(["", f"### Common {expected_type.lower()}s"])
        for node in ranked:
            identifier = node.get("id") if isinstance(node.get("id"), str) else node_label(node)
            connections = counts[identifier]
            suffix = "connection" if connections == 1 else "connections"
            lines.append(f"- {node_label(node)} ({connections} {suffix})")

    papers = typed_nodes(nodes, "Paper")
    if papers:
        recent = sorted(
            papers,
            key=lambda node: (date_value(node), node_label(node).casefold()),
            reverse=True,
        )[:limit]
        lines.extend(["", "### Recently added papers"])
        for paper in recent:
            date = date_value(paper)
            date_suffix = f" ({date})" if date else ""
            lines.append(f"- {markdown_link(node_label(paper), paper.get('url'))}{date_suffix}")

    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--graph", type=Path, required=True, help="Path to .engram/graph.json")
    parser.add_argument("--output", type=Path, required=True, help="Markdown file to write")
    parser.add_argument("--limit", type=int, default=5, help="Maximum entries per section")
    return parser.parse_args()


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    args = parse_args()
    if args.limit < 1:
        LOGGER.error("--limit must be at least 1")
        return 2
    try:
        graph = json.loads(args.graph.read_text(encoding="utf-8"))
    except FileNotFoundError:
        LOGGER.error("Graph not found: %s", args.graph)
        return 1
    except json.JSONDecodeError as error:
        LOGGER.error("Graph is not valid JSON: %s", error)
        return 1
    if not isinstance(graph, Mapping):
        LOGGER.error("Graph root must be a JSON object")
        return 1
    args.output.write_text(build_summary(graph, args.limit), encoding="utf-8")
    LOGGER.info("Wrote deterministic graph summary to %s", args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
